import { useEffect } from 'react'
import { Box, Text } from 'theme-ui'

const Terms = () => {
  useEffect(() => {
    const search = new URL(window.location.href).searchParams
    const privacy = search.get('target') === 'privacy'

    if (privacy) {
      const el = document.getElementById('privacy')
      el?.scrollIntoView({ behavior: 'smooth', block: 'start' })
    }
  }, [])

  return (
    <Box variant="layout.wrapper" p={[1, 4]} py={[4, 7]}>
      <Text as="h1" color="primary">
        Terms and Conditions
      </Text>

      <h2>1. Welcome to Reserve.org and Register!</h2>
      <p>
        These Terms and Conditions ("Terms") govern your access to and use of
        both Reserve.org ("Reserve.org") and app.reserve.org ("Register",
        collectively with Reserve.org, the "Services"). The Services are brought
        to you by ABC Labs, LLC ("ABC Labs," "we," "us," or "our"). To use the
        Services, you must legally be able to enter into this agreement. By
        using or otherwise accessing the Services, you (1) agree that you have
        read and understand these Terms and (2) accept and agree to these Terms.
        If you do not agree to the Terms, then your only recourse is not to use
        the Services.
      </p>
      <p>
        To use the Services, you must be of the age of majority in the
        jurisdiction in which you reside and legally be able to enter into this
        Agreement.
      </p>
      <p>
        Reserve.org and Register provide information about and resources to
        interact with the decentralized application known as the Reserve
        Protocol, which is comprised of open-source smart contracts that are
        deployed on various permissionless public blockchains, such as Ethereum
        (the "Reserve Protocol"). The Reserve Protocol allows for the
        permissionless creation of tokens which are issuable and redeemable by
        anyone for a defined set of other tokens (called "RTokens"). Because the
        Reserve Protocol is open source software that runs autonomously on a
        blockchain network, ABC Labs neither controls nor operates any version
        of the Reserve Protocol on any blockchain network, so you use it at your
        own risk. Collateral assets which back RTokens are held by Reserve
        Protocol smart contracts and are not accessible to ABC Labs.
      </p>
      <p>
        Reserve Rights ("RSR") is a governance token used in the Reserve
        Protocol that permits, among other things, users to participate in
        governance and provide overcollateralization on RTokens. ABC Labs has
        not created, does not control, and takes no responsibility for any
        RToken that has been created on the Reserve Protocol, as all RTokens
        have been permissionlessly created by third parties unaffiliated with
        ABC Labs. ABC Labs does not endorse or recommend any RToken, and you
        agree that your use and interaction with any RToken is at your own risk.
      </p>
      <p>
        RSR holders may stake their RSR to govern specific RTokens. In return
        for providing first-loss capital in the event of a collateral default,
        RSR stakers can receive some of the revenue generated by the collateral
        of that RToken. RSR stakers may participate in governance by
        independently interacting with the relevant smart contracts. Note
        however, that while the voting contracts and Register are intended to
        serve as a convenient way to participate in governance, both are
        experimental and the use of either of them involves a high degree of
        risk. There are numerous ways the voting contracts, the Reserve Protocol
        and Register could fail in an unexpected way, resulting in the total and
        absolute loss of all your funds. That being said, although the voting
        contracts and Reserve Protocol have been audited extensively, there is
        no guarantee that this code or future code will be audited in the
        future. ABC Labs is under no obligation and makes no promises to audit
        any code.
      </p>
      <p>
        <strong>
          ARBITRATION NOTICE: THESE TERMS CONTAIN AN ARBITRATION CLAUSE IN
          SECTION 10. YOU AND WE AGREE THAT ANY DISPUTES RELATING TO THE
          SERVICES WILL BE RESOLVED BY MANDATORY BINDING ARBITRATION, AND YOU
          WAIVE ANY RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN A CLASS-ACTION
          LAWSUIT OR CLASS-WIDE ARBITRATION.
        </strong>
      </p>
      <p>
        <strong>
          LIMITATION OF LIABILITY NOTICE: THE SMART CONTRACTS THAT MAKE UP THE
          RESERVE PROTOCOL ARE BEING LICENSED TO YOU UNDER BLUE OAK MODEL
          LICENSE 1.0.0. THIS LICENSE STATES THAT "AS FAR AS THE LAW ALLOWS,
          THIS SOFTWARE COMES AS IS, WITHOUT ANY WARRANTY OR CONDITION, AND NO
          CONTRIBUTOR WILL BE LIABLE TO ANYONE FOR DAMAGES RELATED TO THIS
          LICENSE, UNDER ANY KIND OF LEGAL CLAIM." BY USING THE SERVICES, AND AS
          FULLY EXPLAINED IN SECTION 7, YOU AGREE THAT ABC LABS, ITS AFFILIATES,
          RTOKEN DEPLOYERS, AND ALL OTHER CONTRIBUTORS TO THE DEVELOPMENT OF THE
          RESERVE PROTOCOL SHALL FACE NO LIABILITY WHATSOEVER FOR ANY LOSS
          RESULTING FROM YOUR USE OF RESERVE.ORG, REGISTER, THE RESERVE
          PROTOCOL, OR RTOKENS.
        </strong>
      </p>

      <h3>Modification of Terms</h3>
      <p>
        We may change or update the Services and any part of the Terms at any
        time, for any reason, at our sole discretion. Once any part of the Terms
        is updated and in effect, you will be bound by the Terms if you continue
        to use the Services. We may, at any time, and without liability to you,
        modify or discontinue all or part of the Services.
      </p>

      <h2>2. Services</h2>
      <p>
        Reserve.org and Register are informational resources about the Reserve
        Protocol; however, they are not the exclusive or sole resources. All
        information provided in connection with your access and use of the
        Services is intended for informational purposes only. While we strive to
        provide accurate and reliable information, we cannot guarantee the
        accuracy, completeness, or timeliness of the information provided. It is
        possible that the information may be outdated or subject to errors or
        omissions. It is also possible that Reserve.org, Register, and/or the
        Reserve Protocol could fail in an unexpected way.
      </p>
      <p>
        Neither we nor any affiliated entity is a party to any transaction on
        the blockchain networks underlying the Reserve Protocol. We do not have
        possession, custody or control over any user's digital assets or funds.
        You understand that when you interact with Reserve Protocol, you always
        retain control over your digital assets. Due to the non-custodial and
        decentralized nature of the technology, we are not intermediaries,
        agents, advisors, or custodians, and we do not have a fiduciary
        relationship or obligation to you regarding any other decisions or
        activities that you make when using our Services.
      </p>
      <p>
        To interact with the Reserve Protocol using Register, you will need to
        connect your self-custodial wallet. Your self-custodial wallet is
        provided by a third party and is governed by separate terms and
        conditions set by the wallet provider. Reviewing and comprehending the
        terms and conditions associated with your chosen self-custodial wallet
        provider is your sole responsibility.
      </p>
      <p>
        Transactions using blockchains may require the payment of gas fees,
        which are essentially network transaction fees paid on every transaction
        that occurs on the selected blockchain network. Please note that gas
        fees are non-refundable. We do not provide any services to users or
        deliver, hold, and/or receive payment for digital assets. We do not
        receive any fees for any transactions or the Services.
      </p>

      <h2>3. Assumption of Risk</h2>
      <p>
        <strong>
          You assume the risks of engaging in novel and experimental technology.
        </strong>
      </p>
      <p>
        Technologies such as smart contracts, cryptographic tokens, and other
        nascent software, applications, and systems that interact with
        blockchain-based networks are experimental, speculative, inherently
        risky, and subject to change. Among other risks, bugs, malfunctions,
        cyberattacks, or changes to the applicable blockchain (e.g., forks)
        could disrupt these technologies and even result in a total loss of
        digital assets. We assume no liability or responsibility for any such
        risks. If you are not comfortable assuming these risks, you should not
        access or engage in transactions using blockchain-based technology.
      </p>
      <p>
        <strong>You acknowledge the risks of using the Services.</strong>
      </p>
      <p>
        You bear sole responsibility for evaluating the Services before using
        them, and all transactions on the blockchain are irreversible, final,
        and without refunds. The Services may be disabled, disrupted, or
        adversely impacted because of sophisticated cyber-attacks, surges in
        activity, computer viruses, and/or other operational or technical
        challenges. You agree to accept these risks and agree that you will not
        seek to hold the ABC Labs Indemnified Parties (as defined below)
        responsible for any consequent losses.
      </p>
      <p>
        <strong>
          You are solely responsible for the security of your self-custodial
          wallet.
        </strong>
      </p>
      <p>
        You understand and agree that you are solely responsible for maintaining
        the security of your self-custodial wallet. You alone are responsible
        for securing your private keys. We do not have access to your private
        keys. Any unauthorized access to your self-custodial wallet by third
        parties could result in the loss or theft of any digital asset or funds
        held in your account. You understand and agree that we have no
        involvement in, and you will not hold us responsible for managing and
        maintaining the security of your self-custodial wallet.
      </p>
      <p>
        <strong>
          We reserve the right to restrict your access to the Services.
        </strong>
      </p>
      <p>
        You agree that we have the right to restrict your access to the Services
        via any technically available methods if we suspect, in our sole
        discretion, that (a) you are using the Services for money laundering or
        any illegal activity; (b) you have engaged in fraudulent activity; (c)
        you have acquired digital assets using inappropriate methods, including
        the use of stolen funds; (d) you are the target of any sanctions
        administered or enforced by the U.S. Department of the Treasury's Office
        of Foreign Assets Control ("OFAC"), the United Nations Security Council,
        or any other legal or regulatory authority in any applicable
        jurisdiction; (e) either you, as an individual or an entity, or your
        wallet address is listed on the Specially Designated Nationals and
        Blocked Persons List or any other sanctions lists administered by OFAC;
        (f) you are located, organized, or resident in a country or territory
        that is, or whose government is, the subject of sanctions, including but
        not limited to Côte d'Ivoire, Cuba, Belarus, Iran, Iraq, Liberia, North
        Korea, Sudan, Venezuela, and Syria; or (g) you have otherwise acted in
        violation of these Terms. If we have a reasonable suspicion that you are
        utilizing the Services for illegal purposes, we reserve the right to
        take whatever action we deem appropriate.
      </p>
      <p>
        <strong>
          We do not guarantee the quality or accessibility of the Services.
        </strong>
      </p>
      <p>
        As a condition to accessing or using the Services, you acknowledge,
        understand, and agree that from time to time, the Services may be
        inaccessible or inoperable for any reason, including, but not limited to
        equipment malfunctions, periodic maintenance, causes beyond our control
        or that we could not reasonably foresee, disruptions and temporary or
        permanent unavailability of underlying blockchain infrastructure or
        unavailability of third-party service providers or external partners for
        any reason.
      </p>
      <p>
        You acknowledge and agree that you will access and use the Services at
        your own risk. You should not engage in blockchain-based transactions
        unless it is suitable given your circumstances and financial resources.
        By using the Services, you represent that you have been, are, and will
        be solely responsible for conducting your own due diligence into the
        risks of a transaction and the underlying smart contracts and digital
        assets.
      </p>

      <h2>4. Taxes</h2>
      <p>
        Users bear sole responsibility for paying any taxes, duties, and
        assessments now or hereafter claimed or imposed by any governmental
        authority associated with their use of the Services and/or payable as a
        result of using and/or exploiting any digital assets and interacting
        with smart contracts.
      </p>

      <h2>5. Prohibited Activities</h2>
      <p>
        You may only use the Services if you comply with these Terms, applicable
        third-party policies, and all applicable laws, rules, regulations, and
        related guidance. The following conduct is prohibited:
      </p>
      <ul>
        <li>
          Using the Services for, or to promote or facilitate, illegal activity
          (including, without limitation, money laundering, financing terrorism,
          tax evasion, buying or selling illegal drugs, contraband, counterfeit
          goods, or illegal weapons).
        </li>
        <li>
          Using the Services in a way that violates any applicable law, rule or
          regulation concerning the trading of securities or derivatives,
          including, but not limited to, the unregistered offering of securities
          and the offering of leveraged and margined commodity products to
          retail customers in the United States.
        </li>
        <li>
          Uploading or transmitting viruses, worms, Trojan horses, time bombs,
          cancel bots, spiders, malware, or any other type of malicious code
          that will or may be used in any way that will affect the functionality
          or operation of the Services.
        </li>
        <li>Interfering with other users' access to or use of the Services.</li>
        <li>
          Interfering with or circumventing the security features of the
          Services or any third party's systems, networks, or resources used in
          the provision of Services.
        </li>
        <li>
          Engaging in any attack, hack, denial-of-service attack, interference,
          or exploit of any smart contract in connection with the use of the
          Service (and operations performed by a user that are technically
          permitted by a smart contract may nevertheless be a violation of these
          Terms and the law).
        </li>
      </ul>
      <p>
        You agree and acknowledge that if you use the Services to engage in
        conduct prohibited by applicable law, we reserve the right to completely
        or partially restrict or revoke your access to the Services at our sole
        discretion. We reserve the right to investigate and prosecute any
        suspected breaches of these Terms. We may disclose any information as
        necessary to satisfy any law, regulation, legal process, or governmental
        request.
      </p>

      <h2>6. Representations, Warranties, Risks, and Disclaimers</h2>
      <h3>No Representation or Warranty</h3>
      <p>
        THE SERVICES AND THE RESERVE PROTOCOL ARE PROVIDED ON AN "AS IS" AND "AS
        AVAILABLE" BASIS. WE AND OUR PARENTS, SUBSIDIARIES, AFFILIATES, RELATED
        COMPANIES, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, REPRESENTATIVES,
        PARTNERS AND LICENSORS (COLLECTIVELY, THE "ABC LABS INDEMNIFIED
        PARTIES"), ALONG WITH RTOKEN DEPLOYERS AND ALL OTHER CONTRIBUTORS TO THE
        DEVELOPMENT OF THE RESERVE PROTOCOL MAKE NO GUARANTEES OF ANY KIND IN
        CONNECTION WITH THE SERVICES AND THE RESERVE PROTOCOL. TO THE MAXIMUM
        EXTENT PERMITTED UNDER APPLICABLE LAW, THE ABC LABS INDEMNIFIED PARTIES,
        RTOKEN DEPLOYERS AND ALL OTHER CONTRIBUTORS TO THE DEVELOPMENT OF THE
        RESERVE PROTOCOL DISCLAIM ALL WARRANTIES AND CONDITIONS, WHETHER EXPRESS
        OR IMPLIED, OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR
        NON-INFRINGEMENT AND DISCLAIM ALL RESPONSIBILITY AND LIABILITY FOR:
      </p>
      <ul>
        <li>
          THE SERVICES AND THE RESERVE PROTOCOL BEING ACCURATE, COMPLETE,
          CURRENT, RELIABLE, UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE.
          INFORMATION AVAILABLE THROUGH THE SERVICES ARE PROVIDED FOR GENERAL
          INFORMATION ONLY AND SHOULD NOT BE RELIED UPON OR USED AS THE SOLE
          BASIS FOR MAKING DECISIONS. ANY RELIANCE ON THE SERVICES IS AT YOUR
          OWN RISK.
        </li>
        <li>
          VIRUSES, WORMS, TROJAN HORSES, TIME BOMBS, CANCEL BOTS, SPIDERS,
          MALWARE, OR OTHER TYPE OF MALICIOUS CODE THAT MAY BE USED IN ANY WAY
          TO AFFECT THE FUNCTIONALITY OR OPERATION OF THE SERVICES.
        </li>
      </ul>

      <h3>Sophistication and Risk of Cryptographic Systems</h3>
      <p>
        By utilizing the Services and the Reserve Protocol, you represent that
        you understand the inherent risks associated with cryptographic systems
        and warrant that you have an understanding of the usage, intricacies,
        and difficulties of using native cryptographic tokens, such as Ether and
        RSR. In general, the underlying software for blockchain networks is open
        source such that anyone can use, copy, modify, and distribute it. By
        using the Services and the Reserve Protocol, you acknowledge and agree
        (i) that the ABC Labs Indemnified Parties are not responsible for the
        Reserve Protocol and the operation of the underlying software and that
        there exists no guarantee of functionality, security, or availability of
        such software and networks; and (ii) that the underlying protocols are
        subject to sudden changes in operating rules (known as "Forks"), and
        that such Forks may materially affect the Reserve Protocol. You
        acknowledge and agree that the ABC Labs Indemnified Parties, RToken
        deployers, and all other contributors to the development of the Reserve
        Protocol assume absolutely no responsibility whatsoever in respect of
        the Reserve Protocol and its underlying software protocols, whether
        Forked or not.
      </p>

      <h3>Application Security</h3>
      <p>
        You acknowledge that Reserve.org, Register, the Reserve Protocol, and
        voting contracts are subject to flaws and acknowledge that you are
        solely responsible for evaluating any code provided by the Services. The
        ABC Labs Indemnified Parties, RToken deployers, and all other
        contributors to the development of the Reserve Protocol disclaim any
        liability as a result of any flaws in the Services or the Reserve
        Protocol.
      </p>

      <h3>Accuracy of the Services</h3>
      <p>
        Although it is intended to provide accurate and timely information on
        Reserve.org and Register, they may not always be entirely accurate,
        complete or current and may also include technical inaccuracies or
        typographical errors. To continue to provide you with the most complete
        and accurate information as possible, information may be changed or
        updated from time to time without notice, including without limitation
        information regarding these Terms. Accordingly, you should verify all
        information before relying on it, and all decisions based on information
        contained on Reserve.org and Register are your sole responsibility and
        the ABC Labs Indemnified Parties shall have no liability for such
        decisions.
      </p>

      <h3>Voting in Cryptographic Systems</h3>
      <p>
        You acknowledge and understand that voting based on smart contracts,
        blockchains and cryptographic systems in general, including the
        so-called onchain voting, is a new and progressing field. Any of the
        risks mentioned above may result in the theft or loss of your digital
        assets and also in various inaccuracies regarding votes you aimed to
        cast, including your vote not being casted at all or casted in an
        unintended way. You represent and warrant that you understand that you
        are solely responsible for the consequences of voting.
      </p>

      <h2>7. Limitations of Liability</h2>
      <p>
        YOU ACKNOWLEDGE AND AGREE THAT YOU ASSUME FULL RESPONSIBILITY FOR YOUR
        USE OF RESERVE.ORG, REGISTER AND THE RESERVE PROTOCOL. YOU ACKNOWLEDGE
        AND AGREE THAT YOUR USE OF THE SERVICES AND THE RESERVE PROTOCOL ARE AT
        YOUR OWN RISK. RECOGNIZING SUCH, YOU UNDERSTAND AND AGREE THAT, TO THE
        FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THE ABC LABS INDEMNIFIED
        PARTIES, RTOKEN DEPLOYERS AND OTHER CONTRIBUTORS TO THE RESERVE PROTOCOL
        WILL NOT BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
        CONSEQUENTIAL, PUNITIVE, EXEMPLARY OR OTHER DAMAGES OF ANY KIND,
        INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE,
        DATA OR OTHER TANGIBLE OR INTANGIBLE LOSSES OR ANY OTHER DAMAGES BASED
        ON CONTRACT, TORT, STRICT LIABILITY OR ANY OTHER THEORY (EVEN IF ADVISED
        OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM THE SERVICES OR THE
        RESERVE PROTOCOL; THE USE OR THE INABILITY TO USE THE SERVICES OR THE
        RESERVE PROTOCOL; UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR
        TRANSMISSIONS OR DATA; ANY ACTIONS WE TAKE OR FAIL TO TAKE AS A RESULT
        OF COMMUNICATIONS YOU SEND TO US; HUMAN ERRORS; TECHNICAL MALFUNCTIONS;
        FAILURES, INCLUDING PUBLIC UTILITY OR TELEPHONE OUTAGES; OMISSIONS,
        INTERRUPTIONS, LATENCY, DELETIONS OR DEFECTS OF ANY DEVICE OR NETWORK,
        PROVIDERS, OR SOFTWARE; INABILITY TO FULLY ACCESS THE SERVICES, RESERVE
        PROTOCOL OR ANY OTHER WEBSITE; OR ANY OTHER MATTER RELATING TO THE
        SERVICES OR THE RESERVE PROTOCOL. THE FOREGOING DISCLAIMER WILL NOT
        APPLY TO THE EXTENT PROHIBITED BY LAW.
      </p>
      <p id="privacy">
        IN NO EVENT WILL THE ABC LABS INDEMNIFIED PARTIES' CUMULATIVE LIABILITY
        TO YOU OR ANY OTHER USER, FROM ALL CAUSES OF ACTION AND ALL THEORIES OF
        LIABILITY EXCEED ONE HUNDRED U.S. DOLLARS (U.S. $100.00).
      </p>

      <h2>8. Privacy Policy</h2>
      <h3>Introduction</h3>
      <p>
        Although we may collect and process information about users of
        Reserve.org and Register in accordance with this Section 8 (the "Privacy
        Policy"), we do not have information about protocol users beyond what is
        already publicly available and recorded on the blockchain. This Privacy
        Policy explains how ABC Labs collects, uses, and shares information in
        connection with the Services as well as your rights and choices
        regarding such information. By using the Services, you also agree to our
        collection, use, and sharing of your information as described in this
        Privacy Policy. If you do not agree, you should not use or access the
        Services.
      </p>

      <h3>Information Collection</h3>
      <p>
        We may collect the following information about you when you use the
        Services:
      </p>
      <ul>
        <li>
          Correspondence and Content: Within any messages you send to us, we may
          collect your name, contact information, and other content included in
          the message.
        </li>
        <li>
          Wallet Address: We may collect the wallet address you use to connect
          your third party self-custodial wallet to Register.
        </li>
        <li>
          Device Information: We may collect information about the device you
          use to access the Interface, such as the device type, operating
          system, and browser type.
        </li>
        <li>
          Usage Information: We collect information about how you use the
          Services. By analyzing this data, we gain a deeper understanding of
          user behavior, which allows us to improve the Services.
        </li>
      </ul>

      <h3>Use of Information</h3>
      <p>
        We may collect and use information for business purposes in accordance
        with the practices described in this Privacy Policy. Our business
        purposes for collecting and using information include:
      </p>
      <ul>
        <li>
          Operating and Managing the Services: To make the Services available to
          you and perform services requested by you, such as responding to your
          comments, questions, and requests, and providing support.
        </li>
        <li>
          Improving the Services: To continually improve the Services and
          fulfill any other legitimate business purpose, as permitted under
          applicable laws.
        </li>
        <li>
          Analytics: We utilize Mixpanel and other similar services to track
          user interactions, preferences, and behavior. This data helps us
          improve our Services and analyze trends in our user base.
        </li>
        <li>
          Security and Compliance with Laws: To operate and maintain the
          security or integrity of the Services, enforce our Terms, and comply
          with applicable laws, lawful requests, and legal process.
        </li>
        <li>
          Facilitating Requests: To comply with your requests, directions, or
          communications.
        </li>
      </ul>

      <h3>Cookies</h3>
      <p>
        We do not use cookies. If we were to, we would use cookies to understand
        how you use our Services so we can improve its design and functionality.
      </p>

      <h3>Children</h3>
      <p>
        To use the Services, you must be of the age of majority in the
        jurisdiction in which you reside and legally be able to enter into the
        Agreement. If you are a parent and believe we have collected personal
        information of a minor, please contact us at contact@reserve.org.
      </p>

      <h3>Additional Disclosures for California Residents</h3>
      <p>
        This section applies only to California residents. The California
        Consumer Privacy Act of 2018 provides additional rights to know, delete,
        and opt-out about your personal information. You have the right to know
        certain details about our data practices within the past twelve (12)
        months, including but not limited to:
      </p>
      <ul>
        <li>
          The categories of personal information we have collected about you;
        </li>
        <li>
          The categories of sources from which the personal information was
          collected;
        </li>
        <li>
          The categories of third parties to whom the personal information was
          disclosed for a business purpose;
        </li>
        <li>
          The specific pieces of personal information we have collected about
          you;
        </li>
        <li>
          A list of the categories of third parties to whom we disclosed such
          information.
        </li>
      </ul>
      <p>
        In addition, you have the right to delete the personal information we
        have collected from you.
      </p>
      <p>
        To exercise any of these rights, please submit a request by emailing us
        at contact@reserve.org. In the request, please specify which right you
        are seeking to exercise and the scope of the request. We may require
        specific information from you to help us verify your identity and
        process your request. If we are unable to verify your identity, we may
        deny your requests to know or delete.
      </p>

      <h3>
        Additional Disclosures for Data Subjects in the European Economic Area
        and the United Kingdom
      </h3>
      <p>
        This section applies only to residents in the European Economic Area
        ("EEA") and the United Kingdom. We act as a controller under the General
        Data Protection Regulations in the EEA and General Data Protection
        Regulations in the United Kingdom ("GDPR") with respect to personal data
        we collect as you use the Services. Controllers are organizations that
        process personal data for their own purposes. GDPR requires a "lawful
        basis" for processing personal data.
      </p>
      <p>Our lawful bases include where:</p>
      <ul>
        <li>
          Consent: You have given consent to the processing of your personal
          data.
        </li>
        <li>
          Contractual Necessity: Processing your personal data is necessary for
          the performance of a contract between you and us.
        </li>
        <li>
          Legal Obligation: Processing your personal data is necessary for
          compliance with a legal obligation.
        </li>
        <li>
          Legitimate Interests: Processing your personal data is necessary for
          the purposes of the legitimate interests pursued by us, provided that
          your interests and fundamental rights and freedoms do not override
          those interests.
        </li>
      </ul>
      <p>The lawful bases of our purposes:</p>
      <ul>
        <li>
          Operating and Managing the Services (Necessary for the Performance of
          our Agreement)
        </li>
        <li>Analytics (Legitimate Interests, Consent)</li>
        <li>Improving the Services (Legitimate Interests, Consent)</li>
        <li>Facilitating Requests (Legitimate Interests, Consent)</li>
        <li>
          Security and Compliance with Laws (Legal Obligation, Legitimate
          Interests)
        </li>
      </ul>
      <p>
        If you are a user in the EEA or the United Kingdom, you maintain certain
        rights under the GDPR. These rights include the right to:
      </p>
      <ul>
        <li>Request access and obtain a copy of your personal data;</li>
        <li>Request rectification or erasure of your personal data;</li>
        <li>Object to or restrict the processing of your personal data;</li>
        <li>Request portability of your personal data.</li>
      </ul>
      <p>
        Additionally, if we have collected and processed your personal data with
        your consent, you have the right to withdraw your consent at any time.
        Notwithstanding the foregoing, we cannot edit or delete information that
        is stored on a particular blockchain. This information may include
        transaction data (i.e., purchases, sales, and transfers) related to your
        blockchain wallet address and any items held by your wallet address.
      </p>
      <p>
        To exercise any of these rights, please contact us at
        contact@reserve.org. We may require specific information from you to
        help us confirm your identity and process your request. If we are unable
        to verify your identity, we may deny your requests to know or delete.
      </p>

      <h2>9. Indemnification</h2>
      <p>
        You agree to release and to indemnify, defend and hold harmless the ABC
        Labs Indemnified Parties, from and against any and all losses,
        liabilities, expenses, damages, costs (including attorneys' fees, fees
        or penalties imposed by any regulatory authority and court costs),
        claims or actions of any kind whatsoever arising or resulting from your
        use of the Services, your violation of these Terms, and your violation
        of any law, rule, or regulation, or the rights of any third party. Each
        of the ABC Labs Indemnified Parties reserves the right, at its own
        expense, to assume exclusive defense and control of any matter otherwise
        subject to indemnification by you and, in such case, you agree to
        cooperate with the ABC Labs Indemnified Parties in the defense of any
        such matter.
      </p>

      <h2>
        10. Arbitration Agreement and Waiver of Rights, Including Class Actions
      </h2>
      <p>
        <strong>
          PLEASE READ THIS SECTION CAREFULLY: IT MAY SIGNIFICANTLY AFFECT YOUR
          LEGAL RIGHTS, INCLUDING YOUR RIGHT TO FILE A LAWSUIT IN COURT AND TO
          HAVE A JURY HEAR YOUR CLAIMS. IT CONTAINS PROCEDURES FOR MANDATORY
          BINDING ARBITRATION AND A CLASS ACTION WAIVER.
        </strong>
      </p>

      <h3>
        Agreement to Attempt to Resolve Disputes Through Good Faith Negotiations
      </h3>
      <p>
        Prior to commencing any legal proceeding against us of any kind,
        including an arbitration as set forth below, you and we agree that we
        will attempt to resolve any dispute, claim, or controversy between us
        arising out of or relating to the agreement or the Services (each, a
        "Dispute" and, collectively, "Disputes") by engaging in good faith
        negotiations. Such good faith negotiations require, at a minimum, that
        the aggrieved party provide a written notice to the other party
        specifying the nature and details of the Dispute. The party receiving
        such notice shall have thirty (30) days to respond to the notice. Within
        sixty (60) days after the aggrieved party sent the initial notice, the
        parties shall meet and confer in good faith by videoconference, or by
        telephone, to try to resolve the Dispute. If the parties are unable to
        resolve the Dispute within ninety (90) days after the aggrieved party
        sent the initial notice, the parties may agree to mediate their Dispute,
        or either party may submit the Dispute to arbitration as set forth
        below.
      </p>

      <h3>Agreement to Arbitrate</h3>
      <p>
        You and we agree that any Dispute that cannot be resolved through the
        procedures set forth above will be settled by arbitration in Reno,
        Nevada, to be administered by JAMS pursuant to its Streamlined
        Arbitration Rules and Procedures. The determination of the arbitrator in
        such proceeding shall be final, binding and non-appealable, and judgment
        upon the award rendered by the arbitrator may be entered in any court
        having jurisdiction thereof. The language of the arbitration shall be
        English. The arbitrator's award of damages must be consistent with the
        terms of the "Limitation of Liability" subsection of these Terms as to
        the types and amounts of damages for which a party may be held liable.
        The prevailing party will be entitled to an award of their reasonable
        attorney's fees and costs. Except as may be required by law, neither a
        party nor its representatives may disclose the existence, content, or
        results of any arbitration hereunder without the prior written consent
        of (all/both) parties.
      </p>
      <p>
        <strong>
          UNLESS YOU TIMELY PROVIDE US WITH AN ARBITRATION OPT-OUT NOTICE PRIOR
          TO USING THE SERVICES, YOU ACKNOWLEDGE AND AGREE THAT YOU AND WE ARE
          EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE AS A
          PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS ACTION OR
          REPRESENTATIVE PROCEEDING.
        </strong>
      </p>

      <h2>11. Waiver of Injunctive or Other Equitable Relief</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, YOU AGREE THAT YOU WILL NOT BE
        PERMITTED TO OBTAIN AN INJUNCTION OR OTHER EQUITABLE RELIEF OF ANY KIND,
        SUCH AS ANY COURT OR OTHER ACTION THAT MAY INTERFERE WITH OR PREVENT THE
        DEVELOPMENT OR EXPLOITATION OF THE SERVICES, OR ANY OTHER WEBSITE,
        APPLICATION, CONTENT, SUBMISSION, PRODUCT, SERVICE, OR INTELLECTUAL
        PROPERTY OWNED, LICENSED, USED OR CONTROLLED BY ANY ABC LABS INDEMNIFIED
        PARTY.
      </p>

      <h2>12. Termination</h2>
      <p>
        This Agreement is effective unless and until terminated by either you or
        us. You may terminate your agreement with us at any time by ceasing all
        access to the Services. If, in our sole judgment, you fail, or we
        suspect that you have failed, to comply with any term or provision of
        the Terms, we reserve the right to terminate our agreement with you and
        deny you access to the Services. We further reserve the right to
        restrict your access to the Services or to stop providing you with all
        or a part of the Services at any time and for no reason, including,
        without limitation, if we reasonably believe: (a) your use of the
        Services exposes us to risk or liability; (b) you are using the Services
        for unlawful purposes; or (c) it is not commercially viable to continue
        providing you with our Services. All of these are in addition to any
        other rights and remedies that may be available to us, whether in equity
        or at law, all of which we expressly reserve.
      </p>

      <h2>13. Severability</h2>
      <p>
        In the event any provision of these Terms is held invalid or
        unenforceable, such holding shall not invalidate or render unenforceable
        any other provision hereof.
      </p>

      <h2>14. Assignment</h2>
      <p>
        These Terms may be assigned without your prior consent to any ABC Labs
        Indemnified Party, or to its successors in the interest of any business
        associated with the Services provided by us. You may not assign or
        transfer any rights or obligations under the Terms without our prior
        written consent.
      </p>

      <h2>15. Entire Agreement</h2>
      <p>
        These Terms set forth the entire understanding of the parties relating
        to the subject matter hereof and supersedes and cancels any prior
        communications, understandings and agreements between the parties
        hereto.
      </p>

      <h2>16. Governing Law</h2>
      <p>
        These Terms shall be governed by and construed in accordance with the
        laws of the State of Delaware including all matters of construction,
        validity, performance, and enforcement and without giving effect to the
        principles of conflict of laws. Any action brought by any party hereto
        shall be brought within the city of Reno, Nevada, in accordance with
        Section 10.
      </p>

      <h2>17. Statute of Limitations</h2>
      <p>
        You agree that regardless of any statute or law to the contrary, any
        claim or cause of action arising out of or related to the Terms or your
        use of the Services must be filed within one (1) year after such claim
        or cause of action arose or be forever barred.
      </p>

      <h2>18. Contact Us</h2>
      <p>
        You may contact us with questions about your use of the Services at{' '}
        <a href="mailto:contact@reserve.org" target="_blank">
          contact@reserve.org
        </a>
        .
      </p>
      <hr />
      <Text as="p" variant="strong">
        Thanks for reading these terms in full. We hope you enjoy using Register
        and the Reserve Protocol! Cheers to you for being part of the DeFi
        revolution and working toward better money :)
      </Text>
    </Box>
  )
}

export default Terms
