export { default as CoinbaseIcon } from './Coinbase'
export { default as LedgerIcon } from './Ledger'
export { default as TrezorIcon } from './Trezor'
export { default as MetamaskIcon } from './Metamask'
export { default as WalletConnectIcon } from './WalletConnect'
export { default as FortmaticIcon } from './Fortmatic'
export { default as RTokenIcon } from './RTokenIcon'
