import type { MessageDescriptor } from '@lingui/core'
import { msg } from '@lingui/core/macro'

const DEFAULT_TRANSCRIPT = msg`Learn more about this DTF, the assets it tracks, how the basket is weighted, and the role each component plays inside the fund.`

const TRANSCRIPTS_BY_SYMBOL: Record<string, MessageDescriptor> = {
  PHOTON: msg`The Reserve AI Photonics DTF (PHOTON) is a weighted basket of public, US-listed photonics companies at the center of the AI buildout. Inside AI data centers, light is replacing copper wire: as AI chips get faster and more data-hungry, the bottleneck shifts from computing the data to moving it, and copper hits a physical wall of heat, power loss, and limited reach. The PHOTON DTF gives you direct exposure to the companies making that shift: the fiber, lasers, transceivers, and optical chips that have become the central nervous system of the AI data center. The basket is composed of companies that generate significant revenue from AI data-center photonics demand, weighted by market capitalization with a 20% cap and a $5B minimum market cap, rebalanced quarterly. The PHOTON DTF bundles Ondo Global Markets tokenized stocks, each of which represents an actual share held in a regulated US brokerage account.`,
  BUILDOUT: msg`The Reserve AI Infrastructure DTF (BUILDOUT) is a weighted basket of public, US-listed semiconductor and hardware companies at the center of the AI buildout. Before any model can run, someone has to build the machine: the chips that compute, the memory that feeds them, the equipment and foundries that make them, and the power that runs it all. The BUILDOUT DTF gives you direct exposure to the picks and shovels of the AI buildout: the semiconductors, memory, manufacturing equipment, networking, and power that every AI dollar flows through first. The basket holds the 25 largest US-listed companies across this AI hardware stack, weighted by market capitalization with a 10% cap, rebalanced quarterly. The BUILDOUT DTF bundles Ondo Global Markets tokenized stocks, each of which represents an actual share held in a regulated US brokerage account.`,
  ROBOTS: msg`The Reserve Robotics DTF (ROBOTS) is a weighted basket of public, US-listed robotics and automation companies at the center of the AI buildout. AI is moving off the screen and into the physical world: the same breakthroughs that taught software to reason are now teaching machines to perceive, decide, and act, and to take on physical labor. The ROBOTS DTF gives you direct exposure to the companies building that transition: the humanoids, surgical robots, factory and warehouse automation, lidar, machine vision, and the chips that let machines navigate the real world. The basket is composed of companies with significant and growing exposure to robotics and automation demand, weighted by market capitalization with a 20% cap and a $2B minimum market cap, rebalanced quarterly. The ROBOTS DTF bundles Ondo Global Markets tokenized stocks, each of which represents an actual share held in a regulated US brokerage account.`,
  POWER: msg`The Reserve AI Power DTF (POWER) is a weighted basket of public, US-listed power companies at the center of the AI buildout. Strip away the software and the chips, and AI comes down to electricity: a single AI data center can draw as much power as a small city, and the grid was never built for hundreds of them. The POWER DTF gives you direct exposure to the companies that generate, move, and condition that electricity: the gas turbines, nuclear plants, grid and electrical equipment, and power chips behind the AI buildout. The basket is composed of companies that generate significant revenue from AI data-center power demand, weighted by market capitalization with a 20% cap and a $10B minimum market cap, rebalanced quarterly. The POWER DTF bundles Ondo Global Markets tokenized stocks, each of which represents an actual share held in a regulated US brokerage account.`,
  NEOCLOUD: msg`The Reserve AI Capacity & Neocloud DTF (NEOCLOUD) is a weighted basket of public, US-listed neocloud and AI data-center companies at the center of the AI buildout. Building an AI data center costs billions, so most companies that need AI computing rent it instead: a new industry of neoclouds and power-rich data-center operators raises the capital, secures the power, and rents out compute by the hour. The NEOCLOUD DTF gives you direct exposure to the companies turning capital, silicon, and electricity into the compute everyone needs: the GPU-cloud operators and the power-rich sites that host them. The basket is composed of companies with significant and growing revenue from AI compute demand, weighted by market capitalization with a 20% cap and a $10B minimum market cap, rebalanced quarterly. The NEOCLOUD DTF bundles Ondo Global Markets tokenized stocks, each of which represents an actual share held in a regulated US brokerage account.`,
}

export const getTranscriptDescriptor = (symbol: string) =>
  TRANSCRIPTS_BY_SYMBOL[symbol.trim().toUpperCase()] ?? DEFAULT_TRANSCRIPT

export const splitTranscriptWords = (transcript: string) =>
  transcript.split(/\s+/).filter(Boolean)
