export default [
  {
    inputs: [
      { internalType: 'address', name: '_daoFeeRegistry', type: 'address' },
      { internalType: 'address', name: '_versionRegistry', type: 'address' },
      {
        internalType: 'address',
        name: '_governorImplementation',
        type: 'address',
      },
      {
        internalType: 'address',
        name: '_timelockImplementation',
        type: 'address',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [], name: 'FailedDeployment', type: 'error' },
  { inputs: [], name: 'FolioDeployer__LengthMismatch', type: 'error' },
  {
    inputs: [
      { internalType: 'uint256', name: 'balance', type: 'uint256' },
      { internalType: 'uint256', name: 'needed', type: 'uint256' },
    ],
    name: 'InsufficientBalance',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'address', name: 'token', type: 'address' }],
    name: 'SafeERC20FailedOperation',
    type: 'error',
  },
  {
    inputs: [],
    name: 'daoFeeRegistry',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'string', name: 'name', type: 'string' },
          { internalType: 'string', name: 'symbol', type: 'string' },
          { internalType: 'address[]', name: 'assets', type: 'address[]' },
          { internalType: 'uint256[]', name: 'amounts', type: 'uint256[]' },
          { internalType: 'uint256', name: 'initialShares', type: 'uint256' },
        ],
        internalType: 'struct IFolio.FolioBasicDetails',
        name: 'basicDetails',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'uint256', name: 'tradeDelay', type: 'uint256' },
          { internalType: 'uint256', name: 'auctionLength', type: 'uint256' },
          {
            components: [
              { internalType: 'address', name: 'recipient', type: 'address' },
              { internalType: 'uint96', name: 'portion', type: 'uint96' },
            ],
            internalType: 'struct IFolio.FeeRecipient[]',
            name: 'feeRecipients',
            type: 'tuple[]',
          },
          { internalType: 'uint256', name: 'folioFee', type: 'uint256' },
        ],
        internalType: 'struct IFolio.FolioAdditionalDetails',
        name: 'additionalDetails',
        type: 'tuple',
      },
      { internalType: 'address', name: 'owner', type: 'address' },
      { internalType: 'address[]', name: 'tradeProposers', type: 'address[]' },
      { internalType: 'address[]', name: 'priceCurators', type: 'address[]' },
    ],
    name: 'deployFolio',
    outputs: [
      { internalType: 'address', name: 'folio_', type: 'address' },
      { internalType: 'address', name: 'folioAdmin_', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'contract IVotes', name: 'stToken', type: 'address' },
      {
        components: [
          { internalType: 'string', name: 'name', type: 'string' },
          { internalType: 'string', name: 'symbol', type: 'string' },
          { internalType: 'address[]', name: 'assets', type: 'address[]' },
          { internalType: 'uint256[]', name: 'amounts', type: 'uint256[]' },
          { internalType: 'uint256', name: 'initialShares', type: 'uint256' },
        ],
        internalType: 'struct IFolio.FolioBasicDetails',
        name: 'basicDetails',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'uint256', name: 'tradeDelay', type: 'uint256' },
          { internalType: 'uint256', name: 'auctionLength', type: 'uint256' },
          {
            components: [
              { internalType: 'address', name: 'recipient', type: 'address' },
              { internalType: 'uint96', name: 'portion', type: 'uint96' },
            ],
            internalType: 'struct IFolio.FeeRecipient[]',
            name: 'feeRecipients',
            type: 'tuple[]',
          },
          { internalType: 'uint256', name: 'folioFee', type: 'uint256' },
        ],
        internalType: 'struct IFolio.FolioAdditionalDetails',
        name: 'additionalDetails',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'uint48', name: 'votingDelay', type: 'uint48' },
          { internalType: 'uint32', name: 'votingPeriod', type: 'uint32' },
          {
            internalType: 'uint256',
            name: 'proposalThreshold',
            type: 'uint256',
          },
          { internalType: 'uint256', name: 'quorumPercent', type: 'uint256' },
          { internalType: 'uint256', name: 'timelockDelay', type: 'uint256' },
          { internalType: 'address', name: 'guardian', type: 'address' },
        ],
        internalType: 'struct IFolioDeployer.GovParams',
        name: 'ownerGovParams',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'uint48', name: 'votingDelay', type: 'uint48' },
          { internalType: 'uint32', name: 'votingPeriod', type: 'uint32' },
          {
            internalType: 'uint256',
            name: 'proposalThreshold',
            type: 'uint256',
          },
          { internalType: 'uint256', name: 'quorumPercent', type: 'uint256' },
          { internalType: 'uint256', name: 'timelockDelay', type: 'uint256' },
          { internalType: 'address', name: 'guardian', type: 'address' },
        ],
        internalType: 'struct IFolioDeployer.GovParams',
        name: 'tradingGovParams',
        type: 'tuple',
      },
      { internalType: 'address[]', name: 'priceCurators', type: 'address[]' },
    ],
    name: 'deployGovernedFolio',
    outputs: [
      { internalType: 'address', name: 'folio', type: 'address' },
      { internalType: 'address', name: 'proxyAdmin', type: 'address' },
      { internalType: 'address', name: 'ownerGovernor', type: 'address' },
      { internalType: 'address', name: 'tradingGovernor', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'folioImplementation',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'governorImplementation',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'timelockImplementation',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'version',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [],
    name: 'versionRegistry',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const
