import { Trans } from '@lingui/macro'
import IconInfo from 'components/info-icon'
import { useAtomValue } from 'jotai'
import {
  rsrExchangeRateAtom,
  rTokenAtom,
  rTokenDistributionAtom,
  rTokenYieldAtom,
} from 'state/atoms'
import { Box, BoxProps, Flex, Grid, Image, Text } from 'theme-ui'

const ExchangeRate = (props: BoxProps) => {
  const rate = useAtomValue(rsrExchangeRateAtom)
  const rToken = useAtomValue(rTokenAtom)

  return (
    <Box variant="layout.borderBox" {...props} padding={4}>
      <Flex sx={{ alignItems: 'center', justifyContent: 'center' }}>
        <Text>
          1 {rToken?.stToken?.symbol ?? 'stRSR'} = {rate} RSR
        </Text>
      </Flex>
    </Box>
  )
}

const Stats = (props: BoxProps) => {
  const distribution = useAtomValue(rTokenDistributionAtom)
  const { stakingApy } = useAtomValue(rTokenYieldAtom)

  return (
    <Box {...props} variant="layout.borderBox" p={0}>
      <Grid gap={0} columns={2}>
        <Box
          p={4}
          sx={{
            borderRight: '1px solid',
            borderBottom: '1px solid',
            borderColor: 'darkBorder',
          }}
        >
          <Text variant="subtitle" mb={3}>
            <Trans>Your stake</Trans>
          </Text>
          <IconInfo
            icon={<Image src="/svgs/trendup.svg" />}
            title="Est. APY"
            text={`${stakingApy}%`}
          />
        </Box>
        <Box
          p={4}
          sx={{ borderBottom: '1px solid', borderColor: 'darkBorder' }}
        >
          <Text variant="subtitle" mb={3}>
            <Trans>Collateral backing</Trans>
          </Text>
          <IconInfo
            icon={<Image src="/svgs/backing.svg" />}
            title="Current"
            text={`${distribution.backing}%`}
          />
        </Box>
        <Box p={4} sx={{ borderRight: '1px solid', borderColor: 'darkBorder' }}>
          <Text variant="subtitle" mb={3}>
            <Trans>Backing + Staked</Trans>
          </Text>
          <IconInfo
            icon={<Image src="/svgs/staked.svg" />}
            title="Current"
            text={`${distribution.backing + distribution.staked}%`}
          />
        </Box>
      </Grid>
    </Box>
  )
}

const About = (props: BoxProps) => (
  <Box variant="layout.borderBox" p={4} {...props}>
    <Text variant="strong" mb={2}>
      <Trans>Staking RSR</Trans>
    </Text>
    <Text as="p" variant="legend">
      <Trans>
        When staking RSR, you are putting your RSR at risk in the case of a
        collateral default in exchange for 1) the rights to govern the RToken
        and 2) for a portion of the revenue generated by the collateral. The
        revenue sent to the staked RSR pool will be distributed amongst RSR
        stakers proportionally to their stake in the pool.
      </Trans>
    </Text>
    <Text variant="strong" mb={2} mt={4}>
      <Trans>Mechanics</Trans>
    </Text>
    <Text as="p" variant="legend">
      <Trans>
        When you stake your RSR, you will receive a stRSR receipt token which
        represents your ownership in the staked RSR contract. As revenue is
        distributed, the receipt token will be redeemable for an increasing
        amount of RSR. If there is a default scenario where the staked RSR is
        slashed, then the receipt token will be redeemable for a decreased
        amount of RSR.
      </Trans>
    </Text>
    <Text variant="strong" mb={2} mt={4}>
      <Trans>Unstaking RSR</Trans>
    </Text>
    <Text as="p" variant="legend">
      <Trans>
        When you unstake your stRSR, there will be a delay (defined by
        governance). This is to eliminate game theory scenarios that would make
        the backstop RSR staked pool less effective because people would
        continually be incentivized to unstake and restake.
      </Trans>
    </Text>
    <Text variant="strong" mb={2} mt={4}>
      <Trans>Risk evaluation</Trans>
    </Text>
    <Text as="p" variant="legend">
      <Trans>
        Please carefully evaluate the RToken before choosing to stake your RSR
        here. If any of the various collaterals of this RToken default, then the
        staked RSR will be the first funds that get auctioned off to make up the
        difference for RToken holders.
      </Trans>
    </Text>
    <Text variant="strong" mb={2} mt={4}>
      <Trans>Governor Alexios</Trans>
    </Text>
    <Text as="p" variant="legend">
      <Trans>
        The description below applies to the default Reserve Governor Alexios.
        If an RToken's deployer opted out of this scheme, please consult with
        the RToken's documentation to understand how staking functions.
      </Trans>
    </Text>
  </Box>
)

const Overview = (props: BoxProps) => {
  return (
    <Box {...props}>
      <ExchangeRate />
      <Stats mt={4} />
      <About mt={4} />
    </Box>
  )
}

export default Overview
