/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { FacadeAct, FacadeActInterface } from "../FacadeAct";

const _abi = [
  {
    inputs: [],
    name: "UIntOutOfBounds",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "contract IRToken",
        name: "rToken",
        type: "address",
      },
    ],
    name: "claimRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes[]",
        name: "data",
        type: "bytes[]",
      },
    ],
    name: "multicall",
    outputs: [
      {
        internalType: "bytes[]",
        name: "results",
        type: "bytes[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IBackingManager",
        name: "bm",
        type: "address",
      },
    ],
    name: "nextRecollateralizationAuction",
    outputs: [
      {
        internalType: "bool",
        name: "canStart",
        type: "bool",
      },
      {
        internalType: "contract IERC20",
        name: "sell",
        type: "address",
      },
      {
        internalType: "contract IERC20",
        name: "buy",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "sellAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IRevenueTrader",
        name: "revenueTrader",
        type: "address",
      },
    ],
    name: "revenueOverview",
    outputs: [
      {
        internalType: "contract IERC20[]",
        name: "erc20s",
        type: "address[]",
      },
      {
        internalType: "bool[]",
        name: "canStart",
        type: "bool[]",
      },
      {
        internalType: "uint256[]",
        name: "surpluses",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "minTradeAmounts",
        type: "uint256[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IRevenueTrader",
        name: "revenueTrader",
        type: "address",
      },
      {
        internalType: "contract IERC20[]",
        name: "toSettle",
        type: "address[]",
      },
      {
        internalType: "contract IERC20[]",
        name: "toStart",
        type: "address[]",
      },
      {
        internalType: "enum TradeKind[]",
        name: "kinds",
        type: "uint8[]",
      },
    ],
    name: "runRevenueAuctions",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class FacadeAct__factory {
  static readonly abi = _abi;
  static createInterface(): FacadeActInterface {
    return new utils.Interface(_abi) as FacadeActInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FacadeAct {
    return new Contract(address, _abi, signerOrProvider) as FacadeAct;
  }
}
