/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Facade, FacadeInterface } from "../Facade";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "main_",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "value",
        type: "int256",
      },
    ],
    name: "IntOutOfBounds",
    type: "error",
  },
  {
    inputs: [],
    name: "basketTokens",
    outputs: [
      {
        internalType: "address[]",
        name: "tokens",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "claimRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "currentAssets",
    outputs: [
      {
        internalType: "address[]",
        name: "tokens",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "main",
    outputs: [
      {
        internalType: "contract MainP0",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "maxIssuable",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "runAuctionsForAllTraders",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "stRSRExchangeRate",
    outputs: [
      {
        internalType: "Fix",
        name: "",
        type: "int192",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalAssetValue",
    outputs: [
      {
        internalType: "Fix",
        name: "total",
        type: "int192",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Facade__factory {
  static readonly abi = _abi;
  static createInterface(): FacadeInterface {
    return new utils.Interface(_abi) as FacadeInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Facade {
    return new Contract(address, _abi, signerOrProvider) as Facade;
  }
}
