/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Main, MainInterface } from "../Main";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "previousAdmin",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newAdmin",
        type: "address",
      },
    ],
    name: "AdminChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IAssetRegistry",
        name: "oldVal",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IAssetRegistry",
        name: "newVal",
        type: "address",
      },
    ],
    name: "AssetRegistrySet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IBackingManager",
        name: "oldVal",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IBackingManager",
        name: "newVal",
        type: "address",
      },
    ],
    name: "BackingManagerSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IBasketHandler",
        name: "oldVal",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IBasketHandler",
        name: "newVal",
        type: "address",
      },
    ],
    name: "BasketHandlerSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "beacon",
        type: "address",
      },
    ],
    name: "BeaconUpgraded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IBroker",
        name: "oldVal",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IBroker",
        name: "newVal",
        type: "address",
      },
    ],
    name: "BrokerSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IDistributor",
        name: "oldVal",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IDistributor",
        name: "newVal",
        type: "address",
      },
    ],
    name: "DistributorSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IFurnace",
        name: "oldVal",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IFurnace",
        name: "newVal",
        type: "address",
      },
    ],
    name: "FurnaceSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [],
    name: "MainInitialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint32",
        name: "oldDuration",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "newDuration",
        type: "uint32",
      },
    ],
    name: "OneshotPauseDurationSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "oldPauser",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newPauser",
        type: "address",
      },
    ],
    name: "OneshotPauserSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IRevenueTrader",
        name: "oldVal",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IRevenueTrader",
        name: "newVal",
        type: "address",
      },
    ],
    name: "RSRTraderSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IRToken",
        name: "oldVal",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IRToken",
        name: "newVal",
        type: "address",
      },
    ],
    name: "RTokenSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IRevenueTrader",
        name: "oldVal",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IRevenueTrader",
        name: "newVal",
        type: "address",
      },
    ],
    name: "RTokenTraderSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IStRSR",
        name: "oldVal",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IStRSR",
        name: "newVal",
        type: "address",
      },
    ],
    name: "StRSRSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint32",
        name: "oldUnpauseAt",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "newUnpauseAt",
        type: "uint32",
      },
    ],
    name: "UnpauseAtSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "implementation",
        type: "address",
      },
    ],
    name: "Upgraded",
    type: "event",
  },
  {
    inputs: [],
    name: "assetRegistry",
    outputs: [
      {
        internalType: "contract IAssetRegistry",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "backingManager",
    outputs: [
      {
        internalType: "contract IBackingManager",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "basketHandler",
    outputs: [
      {
        internalType: "contract IBasketHandler",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "broker",
    outputs: [
      {
        internalType: "contract IBroker",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "distributor",
    outputs: [
      {
        internalType: "contract IDistributor",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "furnace",
    outputs: [
      {
        internalType: "contract IFurnace",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "contract IRToken",
            name: "rToken",
            type: "address",
          },
          {
            internalType: "contract IStRSR",
            name: "stRSR",
            type: "address",
          },
          {
            internalType: "contract IAssetRegistry",
            name: "assetRegistry",
            type: "address",
          },
          {
            internalType: "contract IBasketHandler",
            name: "basketHandler",
            type: "address",
          },
          {
            internalType: "contract IBackingManager",
            name: "backingManager",
            type: "address",
          },
          {
            internalType: "contract IDistributor",
            name: "distributor",
            type: "address",
          },
          {
            internalType: "contract IFurnace",
            name: "furnace",
            type: "address",
          },
          {
            internalType: "contract IBroker",
            name: "broker",
            type: "address",
          },
          {
            internalType: "contract IRevenueTrader",
            name: "rsrTrader",
            type: "address",
          },
          {
            internalType: "contract IRevenueTrader",
            name: "rTokenTrader",
            type: "address",
          },
        ],
        internalType: "struct Components",
        name: "components",
        type: "tuple",
      },
      {
        internalType: "contract IERC20",
        name: "rsr_",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "oneshotPauseDuration_",
        type: "uint32",
      },
    ],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "componentAddr",
        type: "address",
      },
    ],
    name: "isComponent",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "oneshotPauseDuration",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "oneshotPauser",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "poke",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "proxiableUUID",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "rToken",
    outputs: [
      {
        internalType: "contract IRToken",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "rTokenTrader",
    outputs: [
      {
        internalType: "contract IRevenueTrader",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renouncePausership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "rsr",
    outputs: [
      {
        internalType: "contract IERC20",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "rsrTrader",
    outputs: [
      {
        internalType: "contract IRevenueTrader",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IAssetRegistry",
        name: "val",
        type: "address",
      },
    ],
    name: "setAssetRegistry",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IBackingManager",
        name: "val",
        type: "address",
      },
    ],
    name: "setBackingManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IBasketHandler",
        name: "val",
        type: "address",
      },
    ],
    name: "setBasketHandler",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IBroker",
        name: "val",
        type: "address",
      },
    ],
    name: "setBroker",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IDistributor",
        name: "val",
        type: "address",
      },
    ],
    name: "setDistributor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IFurnace",
        name: "val",
        type: "address",
      },
    ],
    name: "setFurnace",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "oneshotPauseDuration_",
        type: "uint32",
      },
    ],
    name: "setOneshotPauseDuration",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "oneshotPauser_",
        type: "address",
      },
    ],
    name: "setOneshotPauser",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IRevenueTrader",
        name: "val",
        type: "address",
      },
    ],
    name: "setRSRTrader",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IRToken",
        name: "val",
        type: "address",
      },
    ],
    name: "setRToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IRevenueTrader",
        name: "val",
        type: "address",
      },
    ],
    name: "setRTokenTrader",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IStRSR",
        name: "val",
        type: "address",
      },
    ],
    name: "setStRSR",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "stRSR",
    outputs: [
      {
        internalType: "contract IStRSR",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unpauseAt",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newImplementation",
        type: "address",
      },
    ],
    name: "upgradeTo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newImplementation",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "upgradeToAndCall",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class Main__factory {
  static readonly abi = _abi;
  static createInterface(): MainInterface {
    return new utils.Interface(_abi) as MainInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Main {
    return new Contract(address, _abi, signerOrProvider) as Main;
  }
}
