/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Main, MainInterface } from "../Main";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IAssetRegistry",
        name: "oldVal",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IAssetRegistry",
        name: "newVal",
        type: "address",
      },
    ],
    name: "AssetRegistrySet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IBackingManager",
        name: "oldVal",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IBackingManager",
        name: "newVal",
        type: "address",
      },
    ],
    name: "BackingManagerSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IBasketHandler",
        name: "oldVal",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IBasketHandler",
        name: "newVal",
        type: "address",
      },
    ],
    name: "BasketHandlerSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IBroker",
        name: "oldVal",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IBroker",
        name: "newVal",
        type: "address",
      },
    ],
    name: "BrokerSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IDistributor",
        name: "oldVal",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IDistributor",
        name: "newVal",
        type: "address",
      },
    ],
    name: "DistributorSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IFurnace",
        name: "oldVal",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IFurnace",
        name: "newVal",
        type: "address",
      },
    ],
    name: "FurnaceSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [],
    name: "Initialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bool",
        name: "oldPaused",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "newPaused",
        type: "bool",
      },
    ],
    name: "PausedSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "oldPauser",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newPauser",
        type: "address",
      },
    ],
    name: "PauserSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IERC20",
        name: "oldVal",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IERC20",
        name: "newVal",
        type: "address",
      },
    ],
    name: "RSRSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IRevenueTrader",
        name: "oldVal",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IRevenueTrader",
        name: "newVal",
        type: "address",
      },
    ],
    name: "RSRTraderSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IRToken",
        name: "oldVal",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IRToken",
        name: "newVal",
        type: "address",
      },
    ],
    name: "RTokenSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IRevenueTrader",
        name: "oldVal",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IRevenueTrader",
        name: "newVal",
        type: "address",
      },
    ],
    name: "RTokenTraderSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IStRSR",
        name: "oldVal",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IStRSR",
        name: "newVal",
        type: "address",
      },
    ],
    name: "StRSRSet",
    type: "event",
  },
  {
    inputs: [],
    name: "assetRegistry",
    outputs: [
      {
        internalType: "contract IAssetRegistry",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "backingManager",
    outputs: [
      {
        internalType: "contract IBackingManager",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "basketHandler",
    outputs: [
      {
        internalType: "contract IBasketHandler",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "broker",
    outputs: [
      {
        internalType: "contract IBroker",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "distributor",
    outputs: [
      {
        internalType: "contract IDistributor",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "furnace",
    outputs: [
      {
        internalType: "contract IFurnace",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "int192",
                name: "maxAuctionSize",
                type: "int192",
              },
              {
                components: [
                  {
                    internalType: "uint16",
                    name: "rTokenDist",
                    type: "uint16",
                  },
                  {
                    internalType: "uint16",
                    name: "rsrDist",
                    type: "uint16",
                  },
                ],
                internalType: "struct RevenueShare",
                name: "dist",
                type: "tuple",
              },
              {
                internalType: "uint256",
                name: "rewardPeriod",
                type: "uint256",
              },
              {
                internalType: "int192",
                name: "rewardRatio",
                type: "int192",
              },
              {
                internalType: "uint256",
                name: "unstakingDelay",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "tradingDelay",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "auctionLength",
                type: "uint256",
              },
              {
                internalType: "int192",
                name: "backingBuffer",
                type: "int192",
              },
              {
                internalType: "int192",
                name: "maxTradeSlippage",
                type: "int192",
              },
              {
                internalType: "int192",
                name: "dustAmount",
                type: "int192",
              },
              {
                internalType: "int192",
                name: "issuanceRate",
                type: "int192",
              },
            ],
            internalType: "struct DeploymentParams",
            name: "params",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "contract IRToken",
                name: "rToken",
                type: "address",
              },
              {
                internalType: "contract IStRSR",
                name: "stRSR",
                type: "address",
              },
              {
                internalType: "contract IAssetRegistry",
                name: "assetRegistry",
                type: "address",
              },
              {
                internalType: "contract IBasketHandler",
                name: "basketHandler",
                type: "address",
              },
              {
                internalType: "contract IBackingManager",
                name: "backingManager",
                type: "address",
              },
              {
                internalType: "contract IDistributor",
                name: "distributor",
                type: "address",
              },
              {
                internalType: "contract IFurnace",
                name: "furnace",
                type: "address",
              },
              {
                internalType: "contract IBroker",
                name: "broker",
                type: "address",
              },
              {
                internalType: "contract IRevenueTrader",
                name: "rsrTrader",
                type: "address",
              },
              {
                internalType: "contract IRevenueTrader",
                name: "rTokenTrader",
                type: "address",
              },
            ],
            internalType: "struct Components",
            name: "components",
            type: "tuple",
          },
          {
            internalType: "contract IERC20",
            name: "rsr",
            type: "address",
          },
          {
            internalType: "contract IGnosis",
            name: "gnosis",
            type: "address",
          },
          {
            internalType: "contract IAsset[]",
            name: "assets",
            type: "address[]",
          },
        ],
        internalType: "struct ConstructorArgs",
        name: "args",
        type: "tuple",
      },
    ],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pauser",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "poke",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "rToken",
    outputs: [
      {
        internalType: "contract IRToken",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "rTokenTrader",
    outputs: [
      {
        internalType: "contract IRevenueTrader",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "rsr",
    outputs: [
      {
        internalType: "contract IERC20",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "rsrTrader",
    outputs: [
      {
        internalType: "contract IRevenueTrader",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IAssetRegistry",
        name: "val",
        type: "address",
      },
    ],
    name: "setAssetRegistry",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IBackingManager",
        name: "val",
        type: "address",
      },
    ],
    name: "setBackingManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IBasketHandler",
        name: "val",
        type: "address",
      },
    ],
    name: "setBasketHandler",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IBroker",
        name: "val",
        type: "address",
      },
    ],
    name: "setBroker",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IDistributor",
        name: "val",
        type: "address",
      },
    ],
    name: "setDistributor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IFurnace",
        name: "val",
        type: "address",
      },
    ],
    name: "setFurnace",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pauser_",
        type: "address",
      },
    ],
    name: "setPauser",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IERC20",
        name: "val",
        type: "address",
      },
    ],
    name: "setRSR",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IRevenueTrader",
        name: "val",
        type: "address",
      },
    ],
    name: "setRSRTrader",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IRToken",
        name: "val",
        type: "address",
      },
    ],
    name: "setRToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IRevenueTrader",
        name: "val",
        type: "address",
      },
    ],
    name: "setRTokenTrader",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IStRSR",
        name: "val",
        type: "address",
      },
    ],
    name: "setStRSR",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "stRSR",
    outputs: [
      {
        internalType: "contract IStRSR",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Main__factory {
  static readonly abi = _abi;
  static createInterface(): MainInterface {
    return new utils.Interface(_abi) as MainInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Main {
    return new Contract(address, _abi, signerOrProvider) as Main;
  }
}
