import type { MessageDescriptor } from '@lingui/core'
import { msg } from '@lingui/core/macro'

import type { ManualReviewState } from '../transaction-composition-manual-scenarios'
import type { ZapperReviewState } from '../transaction-composition-rfq'
import type { StakeReviewState } from '../transaction-composition-stake-support'
import type { AutomatedMintReviewState } from '../transaction-composition-staged-fixtures'
import type { VoteLockReviewState } from '../transaction-composition-vote-lock-support'

export const ZAPPER_STATE_LABELS = {
  'Pre-quote': msg`Enter amount`,
  'Quote search': msg`Finding a route`,
  Review: msg`Review quote`,
  Approval: msg`Review token approval`,
  'Sign order': msg`Sign order`,
  'RFQ execution': msg`Filling the order`,
  'Atomic confirmation': msg`Confirming the transaction`,
  'RFQ outcome': msg`Order complete`,
  'Atomic outcome': msg`Transaction complete`,
  'Quote failure': msg`Quote unavailable`,
  'RFQ recovery': msg`Order needs attention`,
  'Native refund': msg`Refund available`,
  'Route selection': msg`Choose a route`,
  'High-impact acknowledgment': msg`High price impact`,
  'Market-hours advisory': msg`Outside market hours`,
  'Capacity advisory': msg`Capacity limit`,
  'Trading unavailable': msg`Trading unavailable`,
  'CoW redirect · retired': msg`CoW redirect (retired)`,
  Updates: msg`Settlement updates`,
  'Intro call': msg`Introductory call`,
} satisfies Record<ZapperReviewState, MessageDescriptor>

export const AUTOMATED_STATE_LABELS = {
  Introduction: msg`Overview`,
  'Wallet required': msg`Connect a wallet`,
  'Incompatible wallet': msg`Unsupported wallet`,
  'Initial configuration': msg`Enter amount`,
  'Trading paused': msg`Trading paused`,
  'BSC configuration': msg`Enter amount on BNB Chain`,
  'Quote searching': msg`Finding routes`,
  'Quote paused': msg`Quote paused`,
  'Quote unavailable': msg`Quote unavailable`,
  'Input only ready': msg`Review input-only route`,
  'Existing collateral ready': msg`Review existing collateral`,
  'Existing collateral only': msg`Use existing collateral only`,
  'Price unavailable': msg`Price unavailable`,
  'Per-order quote failure': msg`Some quotes unavailable`,
  'Split order quotes': msg`Review split orders`,
  'No swaps needed': msg`No swaps required`,
  'Authorizing orders': msg`Approve orders`,
  'Orders filling': msg`Orders in progress`,
  'Recoverable failure': msg`Action required`,
  'Collateral ready': msg`Collateral ready`,
  'Final mint signing': msg`Confirm final mint`,
  'Cancelled order': msg`Order cancelled`,
  'Wallet unavailable': msg`Wallet unavailable`,
  'Transaction failed': msg`Transaction failed`,
  'Mint complete': msg`Mint complete`,
  'Redeem complete': msg`Redeem complete`,
} satisfies Record<AutomatedMintReviewState, MessageDescriptor>

export const STAKE_STATE_LABELS = {
  'Stake amount': msg`Enter stake amount`,
  Approval: msg`Review token approval`,
  'Approval signing': msg`Approve in wallet`,
  'Stake ready': msg`Ready to stake`,
  'Stake wallet': msg`Confirm stake in wallet`,
  'Stake confirming': msg`Confirming stake`,
  'Stake processing': msg`Staking in progress`,
  'Stake completed': msg`Stake complete`,
  'Unstake amount': msg`Enter unstake amount`,
  'Unstake wallet': msg`Confirm unstake in wallet`,
  'Unstake confirming': msg`Confirming unstake`,
  'Unstake processing': msg`Unstaking in progress`,
  'Unstaking initiated': msg`Unstaking started`,
  'Current delegate': msg`Current delegate`,
  'Delegate ready': msg`Review delegate`,
  'Delegate wallet': msg`Confirm delegation in wallet`,
  'Delegate confirming': msg`Confirming delegation`,
  'Delegate processing': msg`Delegation in progress`,
  'Delegate failed': msg`Delegation failed`,
  'Invalid address': msg`Invalid delegate address`,
  'No staked balance': msg`No staked balance`,
  'Wallet disconnected': msg`Connect a wallet`,
  'Delegate updated': msg`Delegate updated`,
  'Stake failed': msg`Stake failed`,
  'Unstake failed': msg`Unstake failed`,
} satisfies Record<StakeReviewState, MessageDescriptor>

export const VOTE_LOCK_STATE_LABELS = {
  'Lock amount': msg`Enter vote-lock amount`,
  Approval: msg`Review token approval`,
  'Approval signing': msg`Approve in wallet`,
  'Lock ready': msg`Ready to vote-lock`,
  'Lock wallet': msg`Confirm vote-lock in wallet`,
  'Lock confirming': msg`Confirming vote-lock`,
  'Lock processing': msg`Vote-locking in progress`,
  Locked: msg`Vote-lock complete`,
  'Unlock amount': msg`Enter unlock amount`,
  'Unlock wallet': msg`Confirm unlock in wallet`,
  'Unlock confirming': msg`Confirming unlock`,
  'Unlock processing': msg`Unlocking in progress`,
  'Unlock initiated': msg`Unlock started`,
  'Delegated to you': msg`Current delegates`,
  'Delegate ready': msg`Review delegates`,
  'Normal only': msg`Change voting delegate`,
  'Normal signing': msg`Confirm voting delegate`,
  'Fast signing': msg`Confirm emergency delegate`,
  'Fast failed': msg`Emergency delegate failed`,
  'Invalid address': msg`Invalid delegate address`,
  'No locked balance': msg`No vote-locked balance`,
  'Wallet disconnected': msg`Connect a wallet`,
  'Voting delegate updated': msg`Voting delegate updated`,
  'Delegation updated': msg`Delegates updated`,
} satisfies Record<VoteLockReviewState, MessageDescriptor>

export const MANUAL_STATE_LABELS = {
  'Mint requirements': msg`Review mint requirements`,
  'Redeem preview': msg`Review redemption`,
  'Mint empty': msg`Enter mint amount`,
  'Redeem empty': msg`Enter redeem amount`,
  'Basket loading': msg`Loading basket`,
  'Wallet disconnected': msg`Connect a wallet`,
  'Wrong network': msg`Switch network`,
  'Insufficient collateral': msg`Insufficient collateral`,
  'Insufficient shares': msg`Insufficient shares`,
  'Mint restricted': msg`Minting unavailable`,
  'Deprecated DTF': msg`Redemption only`,
  'Approvals signing': msg`Approve assets in wallet`,
  'Approvals confirming': msg`Confirming asset approvals`,
  'Partial approval failure': msg`Some approvals failed`,
  'Revoke signing': msg`Reset approval in wallet`,
  'Revoke confirming': msg`Confirming approval reset`,
  'After revoke': msg`Approval reset complete`,
  'Mint ready': msg`Ready to mint`,
  'Mixed approval progress': msg`Approvals in progress`,
  'Mint wallet': msg`Confirm mint in wallet`,
  'Mint confirming': msg`Confirming mint`,
  'Mint rejected': msg`Mint rejected in wallet`,
  'Mint failed': msg`Mint failed`,
  'Mint outcome': msg`Mint complete`,
  'Redeem wallet': msg`Confirm redeem in wallet`,
  'Redeem confirming': msg`Confirming redemption`,
  'Redeem rejected': msg`Redeem rejected in wallet`,
  'Redeem failed': msg`Redeem failed`,
  'Redeem outcome': msg`Redemption complete`,
} satisfies Record<ManualReviewState, MessageDescriptor>
